// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQbsVyNJsBP_Cp_SnTDVRsclb7mKXi4jk',
    appId: '1:678117286553:web:2819eaf9cdf442d5924e08',
    messagingSenderId: '678117286553',
    projectId: 'api-app-efcef',
    authDomain: 'api-app-efcef.firebaseapp.com',
    storageBucket: 'api-app-efcef.appspot.com',
    measurementId: 'G-C3HMBTV86B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnkGvnQnRFxAJKe8eEOqriKv8BsKZoxwk',
    appId: '1:678117286553:android:80e3205ea1ac9406924e08',
    messagingSenderId: '678117286553',
    projectId: 'api-app-efcef',
    storageBucket: 'api-app-efcef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMc_CWZ8gmrAo9xjZhvLY0nmYmMA_88V0',
    appId: '1:678117286553:ios:8134c423137b2df3924e08',
    messagingSenderId: '678117286553',
    projectId: 'api-app-efcef',
    storageBucket: 'api-app-efcef.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMc_CWZ8gmrAo9xjZhvLY0nmYmMA_88V0',
    appId: '1:678117286553:ios:8134c423137b2df3924e08',
    messagingSenderId: '678117286553',
    projectId: 'api-app-efcef',
    storageBucket: 'api-app-efcef.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQbsVyNJsBP_Cp_SnTDVRsclb7mKXi4jk',
    appId: '1:678117286553:web:c0cd6cdb0bc29809924e08',
    messagingSenderId: '678117286553',
    projectId: 'api-app-efcef',
    authDomain: 'api-app-efcef.firebaseapp.com',
    storageBucket: 'api-app-efcef.appspot.com',
    measurementId: 'G-GC03Z9XBLR',
  );
}
